version: 2.1

orbs:
  skip: theodo/skip@0.0.4

executors:
  defaults_typescript:
    docker:
      - image: circleci/node:12.9

commands:
  yarn-install:
    parameters:
      workspace:
        type: string
    steps:
      - checkout
      - skip/skip_unchanged:
          paths: << parameters.workspace >>
      - attach_workspace:
          at: ~/notion_widget_backend/<< parameters.workspace >>
      - restore_cache:
          key: node-modules-cache-{{ checksum "<< parameters.workspace >>/yarn.lock" }}
      - run:
          working_directory: << parameters.workspace >>
          name: Install front dependencies
          command: yarn
      - save_cache:
          key: node-modules-cache-{{ checksum "<< parameters.workspace >>/yarn.lock" }}
          paths:
            - << parameters.workspace >>/node_modules
      - persist_to_workspace:
          root: ~/notion_widget_backend/<< parameters.workspace >>
          paths:
            - node_modules
            - .env

  yarn-tests:
    parameters:
      workspace:
        type: string
    steps:
      - checkout
      - skip/skip_unchanged:
          paths: << parameters.workspace >>
      - attach_workspace:
          at: ~/notion_widget_backend/<< parameters.workspace >>
      - run:
          working_directory: << parameters.workspace >>
          name: Unit test with coverage
          command: yarn test:coverage
      - store_artifacts:
          path: << parameters.workspace >>/coverage
      - run:
          working_directory: << parameters.workspace >>
          name: Run Typescript checker
          command: yarn tsc

  yarn-linter:
    parameters:
      workspace:
        type: string
    steps:
      - checkout
      - skip/skip_unchanged:
          paths: << parameters.workspace >>
      - attach_workspace:
          at: ~/notion_widget_backend/<< parameters.workspace >>
      - run:
          working_directory: << parameters.workspace >>
          name: Run linter
          command: yarn lint
      - store_artifacts:
          path: << parameters.workspace >>/coverage

  yarn-audit:
    parameters:
      workspace:
        type: string
    steps:
      - checkout
      # yarn-audit is started with a cron.
      # As such we cannot get the frontend dependencies from the workspace like we do with the other jobs. We need to re-install them.
      - run:
          working_directory: << parameters.workspace >>
          name: Install front dependencies
          command: yarn
      - run:
          working_directory: << parameters.workspace >>
          name: Check dependencies
          command: yarn audit-dependencies

jobs:
  yarn-install-back:
    executor: defaults_typescript
    working_directory: ~/notion_widget_backend
    steps:
      - yarn-install:
          workspace: backend

  node-tests:
    executor: defaults_typescript
    working_directory: ~/notion_widget_backend
    environment:
      NODE_ENV: test
    steps:
      - yarn-tests:
          workspace: backend

  node-linter:
    executor: defaults_typescript
    working_directory: ~/notion_widget_backend
    environment:
      NODE_ENV: prod
    steps:
      - yarn-linter:
          workspace: backend

workflows:
  version: 2
  stack:
    jobs:
      - yarn-install-back
      - node-tests:
          requires:
            - yarn-install-back
      - node-linter:
          requires:
            - yarn-install-back
